<?php

/**
 * A Magento 2 module named Magestat/FacebookPixel
 * Copyright (C) 2019 Magestat
 *
 * This file included in Magestat/FacebookPixel is licensed under OSL 3.0
 *
 * http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * Please see LICENSE.txt for the full text of the OSL 3.0 license
 */

/** @var \Magestat\FacebookPixel\Block\PixelCode $block */
?>
<noscript>
    <img height="1"
         width="1"
         style="display:none"
         src="https://www.facebook.com/tr?id=<?= /* @noEscape */ $block->getPixelCode() ?>&ev=PageView&noscript=1"/>
</noscript>
<script type="text/x-magento-init">
{
    "*": {
        "Magestat_FacebookPixel/js/pixel-code": {
            "isCookieEnabled": <?= /* @noEscape */  $block->isCookieEnabled() ?>,
            "currentWebsite": <?= /* @noEscape */ $block->getCurrentWebsiteId() ?>,
            "pixelCode": "<?= /* @noEscape */ $block->getPixelCode() ?>",
            "storeCurrency": "<?= /* @noEscape */ $block->getCurrencyCode() ?>",
            "cookieName": "<?= /* @noEscape */ \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>"
        }
    }
}
</script>
