<?php

/**
 * A Magento 2 module named Magestat/FacebookPixel
 * Copyright (C) 2019 Magestat
 *
 * This file included in Magestat/FacebookPixel is licensed under OSL 3.0
 *
 * http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * Please see LICENSE.txt for the full text of the OSL 3.0 license
 */

/** @var \Magestat\FacebookPixel\Block\Checkout $block */
?>
<script type="text/x-magento-init">
{
    "*": {
        "Magestat_FacebookPixel/js/actions/checkout": {
            "currency": "<?= /* @noEscape */ $block->getCurrencyCode() ?>",
            "contents": <?= /* @noEscape */ $block->getCartContent() ?>,
            "contentIds": <?= /* @noEscape */ $block->getSkuList() ?>,
            "qty": <?= /* @noEscape */ $block->getCheckoutQty() ?>
        }
    }
}
</script>
