<?php
/**
 * A Magento 2 module named Magestat/FacebookPixel
 * Copyright (C) 2019 Magestat
 *
 * This file included in Magestat/FacebookPixel is licensed under OSL 3.0
 *
 * http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * Please see LICENSE.txt for the full text of the OSL 3.0 license
 */

/** @var \Magestat\FacebookPixel\Block\ProductDetail $block */
$product = $block->getCurrentProduct();
?>
<div class="teste">Teste</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magestat_FacebookPixel/js/actions/product-detail": {
                "id": "<?= $block->escapeJs($product->getSku()) ?>",
                "name": "<?= $block->escapeJs($product->getName()) ?>",
                "category": "<?= $block->escapeJs($block->getCurrentCategory()->getName()) ?>"
            }
        }
    }
</script>
