<?php
/** @var \Magestat\FacebookPixel\Block\Success $block */
?>
<script type="text/x-magento-init">
{
    "*": {
        "Magestat_FacebookPixel/js/actions/success": {
            "currency": "<?= /* @noEscape */ $block->getCurrencyCode() ?>",
            "contents": <?= /* @noEscape */ $block->getCartContent() ?>,
            "total": "<?= /* @noEscape */ $block->getCheckoutTotal() ?>",
            "orderId": "<?= $block->escapeJs($block->getOrderId()) ?>"
        }
    }
}
</script>
